sudo: required
services:
  - docker

  before_install:
    - docker build -t nicolepell/react-test -f ./client/Dockerfile.dev
  
  script:
    - docker run nicolepell/react-test npm test -- --coverage
  
  after_success:
    - docker build -t nicolepell/multi-client ./client
    - docker build -t nicolepell/multi-nginx ./nginx
    - docker build -t nicolepell/multi-server ./server
    - docker build -t nicolepell/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push nicolepell/multi-client
    - docker push nicolepell/multi-nginx
    - docker push nicolepell/multi-server
    - docker push nicolepell/multi-worker